spring.application.name=ms_ventas
server.port=8080

# --- trazabilidad y Logs ---#
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO
spring.output.ansi.enabled=ALWAYS

#-- bloqueo de autoinicialización de Spring --#
spring.sql.init.mode=never
#spring.sql.init.data-locations=#
spring.jpa.defer-datasource-initialization=false

#--supabase--#
spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.pjryhukplrppfspdiftt
spring.datasource.password=TiendaBlinblineo12345*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3

#--jpa--#
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=bd_ventas

#--flyway--#
spring.flyway.enabled=true
spring.flyway.default-schema=bd_ventas
spring.flyway.schemas=bd_ventas
spring.flyway.locations=classpath:db/migration
