CREATE SCHEMA IF NOT EXISTS bd_ventas;

-- Tabla principal de la orden de venta
CREATE TABLE IF NOT EXISTS bd_ventas.venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    fecha_venta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_total INT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    folio_boleta VARCHAR(50) NOT NULL
);

-- Tabla para el detalle de los productos comprados
CREATE TABLE IF NOT EXISTS bd_ventas.detalle_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta BIGINT NOT NULL,
    sku_producto VARCHAR(50) NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario INT NOT NULL,
    CONSTRAINT fk_venta FOREIGN KEY (id_venta) REFERENCES bd_ventas.venta(id)
);


INSERT INTO bd_ventas.venta (id_cliente, fecha_venta, monto_total, estado, folio_boleta) 
VALUES (1, CURRENT_TIMESTAMP, 50000, 'COMPLETADO', 'BLIN-001');

INSERT INTO bd_ventas.detalle_venta (id_venta, sku_producto, cantidad, precio_unitario) 
VALUES (1, 'POL-OVER-BLK', 2, 25000);